### PR TITLE
Fix a bug when the directory or file has special characters

### PR DESCRIPTION
**Pull request by yakural**
Hello,I find a bug that when the directory or file name has some special characters(eg.#,+,Some Asia characters like Chinese),the server can't get the correct request path.This commit should fix it(may be):-)

### CODE REVIEW

**Comment by yakural** [comment]
Sorry,I just found that this commit just fix some special characters like(#)，but can't display when its name has some Asia characters and "+"(I don't know why even it is "+" that it still doesn't work).It needs more commit.BTW,it seems that HttpUtility.UrlDecode will convent '+' to space:(

**Comment by dmitriynaumov1024** [comment]
Thanks for investigating that bug. I would be glad to accept your contribution if you fix that. I'm kind of short on time so I may take a day or two to respond /

**Comment by lriy816** [comment]
Ok,I have fixed it.

**Comment by yakural** [comment]
Below is what i did:
1.change the '#' character in href attribute to %23,so we can then decode it.
2.Replace the '+' in request path to %2b(because Httputility.UrlDecode will convert it to space character,we should avoid it)
3.change the field 'Content-Disposition' to support UTF-8
Everything is ok now(may be):)

I'm not sure that are there any special characters that I haven't  take into account,but this server now works well in my own filesystem which has file and directory that contain  Chinese characters,space,'+' and '#'

**Comment by dmitriynaumov1024** [comment]
Good idea, but I wanted to make it more consistent and use only Uri.EscapeDataString and Uri.UnescapeDataString
Ended up rewriting it by myself/

I would like to mention you in README.md for your idea

**Comment by yakural** [comment]
That's ok. I'm just a beginner for asp.net core and want to improve my programming skill from your project.I'm happy to see what i did could make this project better.

**Pull request closed without merging**
